events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Logs
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    # Taille max upload (50 Mo)
    client_max_body_size 50m;

    # Upstream Node.js — port 6000 (interne Docker)
    upstream app {
        server app:6000;
    }

    server {
        listen 80;
        server_name localhost;

        # ── Fichiers statiques (landing page, register, login...)
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ $uri.html /index.html;
        }

        location /u/ {
            try_files $uri /profile.html;
        }

        location /search {
            try_files $uri /search.html;
        }

        location /settings {
            try_files $uri /settings.html;
        }

        # ── API REST → Node.js
        location /api/ {
            proxy_pass              http://app;
            proxy_http_version      1.1;
            proxy_set_header        Host              $host;
            proxy_set_header        X-Real-IP         $remote_addr;
            proxy_set_header        X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_read_timeout      120s;
            proxy_send_timeout      120s;
            proxy_request_buffering off;
        }

        # ── Fichiers uploadés → Node.js
        location /public/uploads/ {
            proxy_pass         http://app;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
        }

        # ── WebSockets Socket.io → Node.js
        location /socket.io/ {
            proxy_pass         http://app;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade    $http_upgrade;
            proxy_set_header   Connection "upgrade";
            proxy_set_header   Host       $host;
            proxy_cache_bypass $http_upgrade;
            proxy_read_timeout 3600s;
        }
    }
}